name: tekartik_app_sembast
description: Sembast for dart app (Web, VM)
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  tekartik_app_sqflite:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sqflite
    version: '>=0.2.0'
  synchronized:
  sembast: ">=3.7.4+3"
  sembast_web: '>=2.4.0+3'
  sembast_sqflite: '>=2.2.0+3'
  sqflite_common_ffi: ">=2.3.4"
  path: ">=1.9.0"
  cv: ">=1.1.0+4"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
resolution: workspace

