name: tekartik_app_common_prefs
description: Dart VM/io/web Prefs helper
version: 0.4.2
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  sembast: ">=3.7.4+3"
  sembast_web:
  tekartik_prefs_sembast:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_sembast
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
  tekartik_prefs_browser:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_browser
    version: '>=0.1.0'
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sembast
    version: '>=0.1.0'
  tekartik_prefs_test:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_test
dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
resolution: workspace

