name: tekartik_app_lints
description: Common dart lints
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  cv: ">=1.1.0+4"
  yaml: ">=3.1.2"
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
    version: '>=0.7.0'
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
dev_dependencies:
  # yaml:
  path: ">=1.9.0"
resolution: workspace
