name: tekartik_app_cv_sdb
description: SDB using cv helpers
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  sembast: ">=3.7.4+3"
  cv: ">=1.1.6"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=1.0.0'
  idb_shim: ">=2.7.1-3"

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
