name: tekartik_app_media
description: Media type constants and helpers
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.0"
dev_dependencies:
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
  test: ">=1.24.0"
resolution: workspace
